name: Rust

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: Version to publish
        

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Version
      if: github.event.inputs.version
      run: |
        new_version="${{ github.event.inputs.version }}"
        old_version=$(cat Cargo.toml | grep "^version =" | awk -F"=" '{print $2}')
        cat Cargo.toml | sed 's/${old_version}/${new_version}/g' > Cargo.toml
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish
      run: cargo publish ${{CARGO_TOKEN}}
      
